### ISSUE TITLE
Question: Does FT create some sort of local cache?

### ISSUE THREAD

**Issue by sgofferj** [SamR1/docker-fittrackee#2]
Does FT create some kind of local cache? I did a make rebuild on the docker setup and the thumbnails are gone and I cannot access any workouts any more. The workout list is fine and I checked with pgadmin - the database seem fine too.

![Screenshot_20210218_094626](https://user-images.githubusercontent.com/3258466/108322809-9744c400-71ce-11eb-9285-d7756059eaad.png)
![Screenshot_20210218_094720](https://user-images.githubusercontent.com/3258466/108322831-9c097800-71ce-11eb-8862-65be0fef1dae.png)
![Screenshot_20210218_094648](https://user-images.githubusercontent.com/3258466/108322822-9a3fb480-71ce-11eb-8b64-7d7199930fe7.png)

**Comment by sgofferj** [comment]
Persistant volumes would be the way to go for persistant data. If I understand it right, the docker philosophy says that a container should always be disposable and all data that need to be persistant should be on persistant volumes. Having the UPLOAD_FOLDER envvar should be fine. I probably should have read the whole docs before installing.

**Comment by sgofferj** [comment]
Here is my fix:

changed .env:
`export UPLOAD_FOLDER=/uploads`

added to docker-compose.yml:
```
    volumes:
      - fittrackee_upload:/uploads:rw
```

**Comment by SamR1** [comment]
Thanks, I updated `docker-compse.yml` and `.env.example` file.
