### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by mako123456** [SamR1/docker-fittrackee#23]
Hi 
I get the error "invalid login data". Never change mail or password - and I am sure that they are correct (password-safe). there ist no error in the log-file...

Is there a way to reset the password in the docker installation?

Best regards!

![fehler](https://user-images.githubusercontent.com/95940359/191298901-ce6d63e8-4a0d-496c-af35-881fb5a792d0.png)

**Comment by SamR1** [comment]
Hi,

yes, it's possible to change the password for a given user with [FitTrackee CLI](https://samr1.github.io/FitTrackee/cli.html#ftcli-users-update) in Docker container.

For instance:
```
$ make shell
root@c511bfc90603:/usr/src/app# ftcli users update Sam --reset-password
```

Then, it should possible to update the password in User Account on FitTrackee.

**Comment by mako123456** [comment]
thank you for the quick reply, made my day :)
