### ISSUE TITLE
ERROR: In file ./.env: environment variable name 'export FITTRACKEE_LOG_DIR' may not contain whitespace.

### ISSUE THREAD

**Issue by voodoopt** [SamR1/docker-fittrackee#24]
ERROR: In file ./.env: environment variable name 'export FITTRACKEE_LOG_DIR' may not contain whitespace.
make: *** [Makefile:5: build] Error 1

I'm not able to do the make :(

**Comment by SamR1** [comment]
Hi,

I didn't reproduced the issue on my installation (Docker Compose version 2.10.2 on Manjaro).
But can you retry after removing all `export ` in **.env**?

for instance:
```
export APP_SETTINGS=fittrackee.config.ProductionConfig
```
to:
```
APP_SETTINGS=fittrackee.config.ProductionConfig
```

**Comment by voodoopt** [comment]
Compile ok but I made other change 
version: '3.8'  to version: '3.3'
I still can't open ip:5000
I have to see what the other problem is ;D

**Comment by SamR1** [comment]
Are there any errors in the application logs?

**Comment by voodoopt** [comment]
Yes,  put again 3.8 because it just created the first service "fittrackee-db"
Error-> 
Successfully tagged docker-fittrackee_fittrackee:latest
fittrackee-db is up-to-date
Creating fittrackee ... error
ERROR: for fittrackee  Cannot create container for service fittrackee: invalid mount config for type "bind": bind source path does not exist: /logs
ERROR: Encountered errors while bringing up the project.

**Comment by SamR1** [comment]
Is the env variable `FITTRACKEE_LOG_DIR` set with an absolute path?

**Comment by voodoopt** [comment]
after change to absolute path works OK 
"FITTRACKEE_LOG_DIR=/home/user/docker-fittrackee/log/"
Thanks for ultra fast suport!

**Comment by SamR1** [comment]
great!
