### ISSUE TITLE
Unraid installation

### ISSUE THREAD

**Issue by tschevko** [SamR1/docker-fittrackee#31]
Hi SamR1,
I want to install docker-fittrackee on my new unraid setup, but I'm a little bit lost how to start here. Can you help here with some hints?
BG

**Comment by 0x09AF** [comment]
Do you have `docker` installed? `git`?  
Did you follow the commands in `README.md`?

**Comment by trash-it** [comment]
@0x09AF on unraid docker is always installed. But in standard case you won't work on command line nor with docker compose. You can, but it's not the recommended way. the common container management is just a gui in which set the image from github or docker, and then you can set container variables and path and stuff.

**Comment by SamR1** [comment]
The repo will be archived as a [docker image](https://samr1.github.io/FitTrackee/en/installation.html#id6) is now available.
