### ISSUE TITLE
ERROR:  relation "app_config" does not exist at character 563

### ISSUE THREAD

**Issue by wforumw** [SamR1/docker-fittrackee#33]
Hi,
I have installed fittrackee following the README
When I try to register my first user I get 

![register](https://github.com/user-attachments/assets/424c8d9e-b926-4217-88b2-4d29036a8348)

In the fittrackee.log I see
```
fittrackee - ERROR - Exception on /api/config [GET]
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/src/app/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "app_config" does not exist
LINE 2: FROM app_config
```
Have I overlooked something?
Many thanks!

**Comment by SamR1** [comment]
Hi,

It seems migrations are not executed.
Does the problem remain after running the following command?
```
$ make migrate
```

By the way, the repo is no longer maintained, a [docker image](https://hub.docker.com/r/fittrackee/fittrackee/tags) is now available (I'll update the `README.md`). 
You can find an example of [`docker-compose.yml`](https://github.com/SamR1/FitTrackee/blob/master/docker-compose.yml) in [FitTrackee](https://github.com/SamR1/FitTrackee) repo.  

Documentation: https://samr1.github.io/FitTrackee/en/installation.html#id6

**Comment by wforumw** [comment]
TXS, I installed the docker image now and it works
